INSERT INTO played(userid, charid, games) VALUES (1, 1 , 0);
INSERT INTO played(userid, charid, games) VALUES (1, 2 , 0);
INSERT INTO played(userid, charid, games) VALUES (1, 3 , 0);
INSERT INTO played(userid, charid, games) VALUES (1, 4 , 0);
INSERT INTO played(userid, charid, games) VALUES (1, 5 , 0);
INSERT INTO played(userid, charid, games) VALUES (1, 6 , 0);
INSERT INTO played(userid, charid, games) VALUES (1, 7 , 0);
INSERT INTO played(userid, charid, games) VALUES (1, 8 , 0);
INSERT INTO played(userid, charid, games) VALUES (1, 9 , 0);